from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

from shadow_sandbox.api.router import API_ROUTE_CONTRACT

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "web/src/api/generated-contract.ts"


def _path_type(path: str) -> str:
    relative = path.removeprefix("/api/v1")
    if "{" not in relative:
        return json.dumps(relative)
    template = re.sub(r"\{[A-Za-z_][A-Za-z0-9_]*\}", "${string}", relative)
    return f"`{template}`"


def _path_pattern(path: str) -> str:
    relative = path.removeprefix("/api/v1")
    parts = relative.split("/")
    pattern = "/".join(
        "[^/]+" if part.startswith("{") and part.endswith("}") else re.escape(part)
        for part in parts
    )
    escaped = pattern.replace("/", "\\/")
    return f"^{escaped}$"


def render() -> str:
    canonical = json.dumps(API_ROUTE_CONTRACT, separators=(",", ":"))
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    grouped: dict[str, list[str]] = {"GET": [], "POST": [], "PATCH": []}
    for method, path in API_ROUTE_CONTRACT:
        grouped.setdefault(method, []).append(_path_type(path))

    def union(name: str, values: list[str]) -> str:
        body = "\n".join(f"  | {value}" for value in values)
        return f"export type {name} =\n{body}\n"

    return "\n".join(
        (
            "// Generated by tools/generate_frontend_client.py. Do not edit by hand.",
            f"export const API_CONTRACT_DIGEST = '{digest}' as const",
            f"export const API_ROUTE_COUNT = {len(API_ROUTE_CONTRACT)} as const",
            "export type ApiMethod = 'GET' | 'POST' | 'PATCH'",
            union("GetPath", grouped["GET"]),
            union("PostPath", grouped["POST"]),
            union("PatchPath", grouped["PATCH"]),
            "export type ApiPath = GetPath | PostPath | PatchPath",
            "const API_ROUTE_PATTERNS: readonly (readonly [ApiMethod, RegExp])[] = [",
            *(f"  ['{method}', /{_path_pattern(path)}/]," for method, path in API_ROUTE_CONTRACT),
            "] as const",
            "",
            "export function matchesApiRoute(method: ApiMethod, path: string): path is ApiPath {",
            "  return API_ROUTE_PATTERNS.some(([candidate, pattern]) => candidate === method && pattern.test(path))",
            "}",
            "",
            "export function assertApiRoute(method: ApiMethod, path: string): asserts path is ApiPath {",
            "  if (!matchesApiRoute(method, path)) throw new Error(`API route contract rejected ${method} ${path}`)",
            "}",
            "",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the typed frontend API route contract")
    parser.add_argument("--check", action="store_true", help="fail when the checked-in output drifts")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            print(f"FRONTEND_API_CONTRACT_DRIFT: regenerate {TARGET.relative_to(ROOT)}")
            return 1
        print(
            f"Frontend API contract matches {len(API_ROUTE_CONTRACT)} backend routes "
            f"({hashlib.sha256(expected.encode()).hexdigest()})."
        )
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Generated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
