// Generated by tools/generate_frontend_client.py. Do not edit by hand.
export const API_CONTRACT_DIGEST = 'b0713941bca1988b01b3f5b9fb004bfc47da950e1328d399cc943971d11a103e' as const
export const API_ROUTE_COUNT = 89 as const
export type ApiMethod = 'GET' | 'POST' | 'PATCH'
export type GetPath =
  | "/health/live"
  | "/health/ready"
  | "/version"
  | "/auth/config"
  | "/me"
  | "/permissions"
  | `/asset-models/${string}`
  | `/asset-model-versions/${string}`
  | `/asset-model-versions/${string}/topology`
  | `/scenarios/${string}`
  | `/scenario-versions/${string}`
  | `/runs/${string}`
  | `/runs/${string}/timeline`
  | `/runs/${string}/tasks`
  | `/runs/${string}/signals/${string}/events`
  | `/connectors/${string}/health`
  | `/runs/${string}/quality`
  | `/runs/${string}/anomalies`
  | `/runs/${string}/residuals`
  | `/runs/${string}/consistency-observations`
  | `/runs/${string}/evidence`
  | `/evidence/${string}`
  | `/runs/${string}/symptoms`
  | `/runs/${string}/evidence-timeline`
  | `/runs/${string}/hypotheses`
  | `/runs/${string}/causal-subgraph`
  | `/runs/${string}/check-plan`
  | "/approvals/inbox"
  | `/approvals/${string}`
  | `/actions/${string}`
  | `/runs/${string}/actions`
  | `/replays/${string}`
  | `/experiments/${string}`
  | `/experiments/${string}/comparison`
  | `/experiments/${string}/episodes`
  | `/evaluations/${string}`
  | `/evaluations/${string}/slices`
  | `/evaluations/${string}/episodes`
  | `/reports/${string}`
  | `/import-jobs/${string}`
  | `/datasets/${string}`
  | `/edge-gateways/${string}/health`
  | "/admin/system-health"
  | "/admin/quotas"
  | "/admin/version-registry"
  | "/audit-records"

export type PostPath =
  | "/asset-models"
  | `/asset-models/${string}/validate`
  | `/asset-models/${string}/publish`
  | "/scenarios"
  | `/scenarios/${string}/validate`
  | `/scenarios/${string}/preview`
  | `/scenarios/${string}/publish`
  | `/scenario-suites/${string}/validate`
  | `/scenario-suites/${string}/publish`
  | `/scenario-suites/${string}/expand`
  | "/runs"
  | `/runs/${string}/pause`
  | `/runs/${string}/resume`
  | `/runs/${string}/cancel`
  | `/runs/${string}/retry`
  | `/runs/${string}/exports/parquet`
  | `/runs/${string}/quality-and-detect`
  | `/runs/${string}/residuals-and-consistency`
  | `/runs/${string}/materialize-evidence`
  | `/runs/${string}/hypotheses`
  | `/runs/${string}/check-plans`
  | `/check-plans/${string}/reorder-preview`
  | "/approval-requests"
  | `/approvals/${string}/decide`
  | `/approvals/${string}/transfer`
  | `/approvals/${string}/revoke`
  | "/actions"
  | `/runs/${string}/replays`
  | "/experiments"
  | "/evaluations"
  | "/release-gates/evaluate"
  | `/release-gates/${string}/promote`
  | "/reports"
  | "/import-sources"
  | "/import-sources/profile"
  | "/mappings/validate"
  | "/import-jobs"
  | "/edge-gateways/register"
  | "/edge-gateways/rotate"
  | "/edge-gateways/event-batches"
  | "/edge-gateways/heartbeats"

export type PatchPath =
  | `/asset-models/${string}`
  | `/scenarios/${string}`

export type ApiPath = GetPath | PostPath | PatchPath
const API_ROUTE_PATTERNS: readonly (readonly [ApiMethod, RegExp])[] = [
  ['GET', /^\/health\/live$/],
  ['GET', /^\/health\/ready$/],
  ['GET', /^\/version$/],
  ['GET', /^\/auth\/config$/],
  ['GET', /^\/me$/],
  ['GET', /^\/permissions$/],
  ['POST', /^\/asset\-models$/],
  ['GET', /^\/asset\-models\/[^\/]+$/],
  ['PATCH', /^\/asset\-models\/[^\/]+$/],
  ['POST', /^\/asset\-models\/[^\/]+\/validate$/],
  ['POST', /^\/asset\-models\/[^\/]+\/publish$/],
  ['GET', /^\/asset\-model\-versions\/[^\/]+$/],
  ['GET', /^\/asset\-model\-versions\/[^\/]+\/topology$/],
  ['POST', /^\/scenarios$/],
  ['GET', /^\/scenarios\/[^\/]+$/],
  ['PATCH', /^\/scenarios\/[^\/]+$/],
  ['POST', /^\/scenarios\/[^\/]+\/validate$/],
  ['POST', /^\/scenarios\/[^\/]+\/preview$/],
  ['POST', /^\/scenarios\/[^\/]+\/publish$/],
  ['GET', /^\/scenario\-versions\/[^\/]+$/],
  ['POST', /^\/scenario\-suites\/[^\/]+\/validate$/],
  ['POST', /^\/scenario\-suites\/[^\/]+\/publish$/],
  ['POST', /^\/scenario\-suites\/[^\/]+\/expand$/],
  ['POST', /^\/runs$/],
  ['GET', /^\/runs\/[^\/]+$/],
  ['GET', /^\/runs\/[^\/]+\/timeline$/],
  ['GET', /^\/runs\/[^\/]+\/tasks$/],
  ['POST', /^\/runs\/[^\/]+\/pause$/],
  ['POST', /^\/runs\/[^\/]+\/resume$/],
  ['POST', /^\/runs\/[^\/]+\/cancel$/],
  ['POST', /^\/runs\/[^\/]+\/retry$/],
  ['GET', /^\/runs\/[^\/]+\/signals\/[^\/]+\/events$/],
  ['POST', /^\/runs\/[^\/]+\/exports\/parquet$/],
  ['GET', /^\/connectors\/[^\/]+\/health$/],
  ['POST', /^\/runs\/[^\/]+\/quality\-and\-detect$/],
  ['GET', /^\/runs\/[^\/]+\/quality$/],
  ['GET', /^\/runs\/[^\/]+\/anomalies$/],
  ['POST', /^\/runs\/[^\/]+\/residuals\-and\-consistency$/],
  ['GET', /^\/runs\/[^\/]+\/residuals$/],
  ['GET', /^\/runs\/[^\/]+\/consistency\-observations$/],
  ['POST', /^\/runs\/[^\/]+\/materialize\-evidence$/],
  ['GET', /^\/runs\/[^\/]+\/evidence$/],
  ['GET', /^\/evidence\/[^\/]+$/],
  ['GET', /^\/runs\/[^\/]+\/symptoms$/],
  ['GET', /^\/runs\/[^\/]+\/evidence\-timeline$/],
  ['POST', /^\/runs\/[^\/]+\/hypotheses$/],
  ['GET', /^\/runs\/[^\/]+\/hypotheses$/],
  ['GET', /^\/runs\/[^\/]+\/causal\-subgraph$/],
  ['POST', /^\/runs\/[^\/]+\/check\-plans$/],
  ['GET', /^\/runs\/[^\/]+\/check\-plan$/],
  ['POST', /^\/check\-plans\/[^\/]+\/reorder\-preview$/],
  ['POST', /^\/approval\-requests$/],
  ['GET', /^\/approvals\/inbox$/],
  ['GET', /^\/approvals\/[^\/]+$/],
  ['POST', /^\/approvals\/[^\/]+\/decide$/],
  ['POST', /^\/approvals\/[^\/]+\/transfer$/],
  ['POST', /^\/approvals\/[^\/]+\/revoke$/],
  ['POST', /^\/actions$/],
  ['GET', /^\/actions\/[^\/]+$/],
  ['GET', /^\/runs\/[^\/]+\/actions$/],
  ['POST', /^\/runs\/[^\/]+\/replays$/],
  ['GET', /^\/replays\/[^\/]+$/],
  ['POST', /^\/experiments$/],
  ['GET', /^\/experiments\/[^\/]+$/],
  ['GET', /^\/experiments\/[^\/]+\/comparison$/],
  ['GET', /^\/experiments\/[^\/]+\/episodes$/],
  ['POST', /^\/evaluations$/],
  ['GET', /^\/evaluations\/[^\/]+$/],
  ['GET', /^\/evaluations\/[^\/]+\/slices$/],
  ['GET', /^\/evaluations\/[^\/]+\/episodes$/],
  ['POST', /^\/release\-gates\/evaluate$/],
  ['POST', /^\/release\-gates\/[^\/]+\/promote$/],
  ['POST', /^\/reports$/],
  ['GET', /^\/reports\/[^\/]+$/],
  ['POST', /^\/import\-sources$/],
  ['POST', /^\/import\-sources\/profile$/],
  ['POST', /^\/mappings\/validate$/],
  ['POST', /^\/import\-jobs$/],
  ['GET', /^\/import\-jobs\/[^\/]+$/],
  ['GET', /^\/datasets\/[^\/]+$/],
  ['POST', /^\/edge\-gateways\/register$/],
  ['POST', /^\/edge\-gateways\/rotate$/],
  ['POST', /^\/edge\-gateways\/event\-batches$/],
  ['POST', /^\/edge\-gateways\/heartbeats$/],
  ['GET', /^\/edge\-gateways\/[^\/]+\/health$/],
  ['GET', /^\/admin\/system\-health$/],
  ['GET', /^\/admin\/quotas$/],
  ['GET', /^\/admin\/version\-registry$/],
  ['GET', /^\/audit\-records$/],
] as const

export function matchesApiRoute(method: ApiMethod, path: string): path is ApiPath {
  return API_ROUTE_PATTERNS.some(([candidate, pattern]) => candidate === method && pattern.test(path))
}

export function assertApiRoute(method: ApiMethod, path: string): asserts path is ApiPath {
  if (!matchesApiRoute(method, path)) throw new Error(`API route contract rejected ${method} ${path}`)
}
