apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: industrial-shadow
resources:
  - namespace.yaml
  - service-accounts.yaml
  - config.yaml
  - workloads.yaml
  - network-policies.yaml
  - migration-job.yaml
  - backup-cronjob.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: industrial-shadow-sandbox
